
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore: # files and folders for processing
  - src/test/*
  - src/main/scala/de.htwg.se.SevenSteps/aview/*
  - src/main/scala/de.htwg.se.SevenSteps/Factory.scala
  - src/main/scala/de.htwg.se.SevenSteps/SevenSteps.scala
  - src/main/scala/de.htwg.se.SevenSteps/SevenStepsModule.scala
  - **/*Mock

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
